### ISSUE TITLE
DEFCAL definition is inconsistent with the examples

### ISSUE THREAD

**Issue by notmgsk** [quil-lang/quil#66]
The [spec's](https://quil-lang.github.io/#12-6Defining-Calibrations) definition of `DEFCAL` is
```
⟨Calibration Definition⟩ ::= DEFCAL ⟨Modifier⟩*⟨Identifier⟩ ( ⟨Parameters⟩ ) ⟨Qubit⟩+ : ⟨Instruction⟩+
```
The spec then uses these as examples
```
DEFCAL RX(%theta) %qubit:

...

DEFCAL RZ(%theta) %qubit:
    SHIFT-PHASE %qubit "xy" %theta
```

In particular, both use the `%` prefix for the qubit name. However, the definition uses `⟨Qubit⟩` as the type, which restricts values to non-negative integers.

I think there are two problems here:
* `DEFCAL` should take `⟨Formal Qubit⟩` which would allow identifiers (e.g. `DEFCAL I q: ...`)
* The examples should remove the `%` prefix where applicable

**Comment by macrologist** [comment]
@notmgsk  Merged a change  (see #80). I'm closing this issue but will re-open if this does seem quite right.
